INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Alabama', 'June 5th, 2018', '2018-07-17', 'No', '7','2018-06-05');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Alaska', 'August 21st, 2018', null, 'No', '1', '2018-08-21');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('American Samoa', null , null , null , '1 Delegate', null);
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Arizona', 'August 28th, 2018', null, 'Yes', '9', '2018-08-28');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Arkansas', 'May 22nd, 2018', '2018-06-19', 'No', '4', '2018-05-22');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('California', 'June 5th, 2018', null, 'Yes', '53', '2018-06-05');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Colorado', 'June 26th, 2018', null, 'No', '7', '2018-06-26');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Connecticut', 'August 14th, 2018', null, 'Yes', '5', '2018-08-14');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Delaware', 'September 6th, 2018', null, 'Yes', '1', '2018-09-06');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('District of Columbia', 'June 19th, 2018', null, null, '1 Delegate', '2018-06-19');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Florida', 'August 29th, 2018', null, 'Yes', '27', '2018-08-29');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Georgia', 'May 22nd, 2018', '2018-07-24', 'No', '14', '2018-05-22');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Guam', 'August 25th, 2018', null, null, '1 Delegate', '2018-08-25');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Hawaii', 'August 11th, 2018', null, 'Yes', '2', '2018-08-11');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Idaho', 'May 15th, 2018', null, 'No', '2', '2018-05-15');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Illinois', 'March 20th, 2018', null, 'No', '18', '2018-03-20');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Indiana', 'May 8th, 2018', null, 'Yes', '9', '2018-05-08');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Iowa', 'June 5th, 2018', null, 'No', '4', '2018-06-05');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Kansas', 'August 7th, 2018', null, 'No', '4', '2018-08-07');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Kentucky', 'May 22nd, 2018', null, 'No', '6', '2018-05-22');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Louisiana', 'November 6th, 2018', null, 'No', '6', '2018-11-06');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Maine', 'June 12th, 2018', null, 'Yes', '2', '2018-06-12');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Maryland', 'June 26, 2018', null, 'Yes', '8', '2018-06-26');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Massachusetts', 'September 18th, 2018', null, 'Yes', '9', '2018-09-18');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Michigan', 'August 7th, 2018', null, 'Yes', '14', '2018-08-07');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Minnesota', 'August 14th, 2018', null, 'Yes', '8', '2018-08-14');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Mississippi', 'June 6th, 2018', null, 'Yes', '4', '2018-06-05');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Missouri', 'August 7th, 2018', null, 'Yes', '8', '2018-08-07');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Montana', 'June 5th, 2018', null, 'Yes', '1', '2018-06-05');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Nebraska', 'June 15h, 2018', null, 'Yes', '3', '2018-05-15');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Nevada', 'June 12th, 2018', null, 'Yes', '4', '2018-06-12');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('New Hampshire', 'September 11th, 2018', null, 'No', '2', '2018-09-11');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('New Jersey', 'June 5th, 2018', null, 'Yes', '12', '2018-06-05');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('New Mexico', 'June 5th, 2018', null, 'Yes', '3', '2018-06-05');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('New York', 'September 11th, 2018', null, 'Yes', '27', '2018-09-11');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('North Carolina', 'May 8th, 2018', '2018-07-17', '13', '2018-05-08');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('North Dakota', 'June 12th, 2018', null, 'Yes', '1', '2018-06-12');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Ohio', 'May 8th, 2018', null, 'Yes', '16', '2018-05-08');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Oklahoma', 'June 26th, 2018', '2018-08-28', 'No', '5', '2018-06-26');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Oregon', 'May 15th, 2018', null, 'No', '5', '2018-05-15');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Pennsylvania', 'May 15th, 2018', null, 'Yes', '18','2018-05-15' );
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Puerto Rico', null, null, null, '1 Resident', null);
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Rhode Island', 'September 12th, 2018', null, 'Yes', '2', '2018-09-12');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('South Carolina', 'June 12th, 2018', '2018-06-26', 'No', '7', '2018-06-12');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('South Dakota', 'June 5th, 2018', null, 'No', '1', '2018-06-05');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Tennessee', 'August 2nd, 2018', null, 'Yes', '9', '2018-08-02');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Texas', 'March 6th, 2018', '2018-05-22', 'Yes', '36', '2018-03-06');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Utah', 'June 26th, 2018', null, 'Yes', '4', '2018-06-26');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Vermont', 'August 14th, 2018', null, 'Yes', '1', '2018-08-14');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Virgin Islands', 'August 4th, 2018', null, null, '1 Delegate', '2018-08-04');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Virginia', 'June 12th, 2018', null, 'Yes', '11', '2018-06-12');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Washington', 'August 7th, 2018', null, 'Yes', '10', '2018-08-07');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('West Virginia', 'May 8th, 2018', null, 'Yes', '3', '2018-05-08');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Wisconsin', 'August 14th, 2018', null, 'Yes', '8', '2018-08-14');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives, electionDateByDate) VALUES ('Wyoming', 'August 21, 2018', null, 'Yes', '1', '2018-08-21');