INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Alabama', '2018-06-05', '2018-07-17', 'No', '7');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Alaska', '2018-08-21', null, 'No', '1');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('American Samoa', null , null , null , '1 Delegate');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Arizona', '2018-08-28', null, 'Yes', '9');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Arkansas', '2018-05-22', '2018-06-19', 'No', '4');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('California', '2018-06-05', null, 'Yes', '53');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Colorado', '2018-06-26', null, 'No', '7');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Connecticut', '2018-08-14', null, 'Yes', '5');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Delaware', '2018-09-06', null, 'Yes', '1');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('District of Columbia', '2018-06-19', null, null, '1 Delegate');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Florida', '2018-08-29', null, 'Yes', '27');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Georgia', '2018-05-22', '2018-07-24', 'No', '14');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Guam', '2018-08-25', null, null, '1 Delegate');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Hawaii', '2018-08-11', null, 'Yes', '2');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Idaho', '2018-05-15', null, 'No', '2');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Illinois', '2018-03-20', null, 'No', '18');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Indiana', '2018-05-08', null, 'Yes', '9');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Iowa', '2018-06-05', null, 'No', '4');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Kansas', '2018-08-07', null, 'No', '4');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Kentucky', '2018-05-22', null, 'No', '6');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Louisiana', '2018-11-06', null, 'No', '6');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Maine', '2018-06-12', null, 'Yes', '2');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Maryland', '2018-06-26', null, 'Yes', '8');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Massachusetts', '2018-09-18', null, 'Yes', '9');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Michigan', '2018-08-07', null, 'Yes', '14');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Minnesota', '2018-08-14', null, 'Yes', '8');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Mississippi', '2018-06-05', null, 'Yes', '4');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Missouri', '2018-08-07', null, 'Yes', '8');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Montana', '2018-06-05', null, 'Yes', '1');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Nebraska', '2018-05-15', null, 'Yes', '3');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Nevada', '2018-06-12', null, 'Yes', '4');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('New Hampshire', '2018-09-11', null, 'No', '2');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('New Jersey', '2018-06-05', null, 'Yes', '12');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('New Mexico', '2018-06-05', null, 'Yes', '3');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('New York', '2018-06-28', null, 'Yes', '27');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('North Carolina', '2018-05-08', '2018-07-17', '13');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('North Dakota', '2018-06-12', null, 'Yes', '1');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Ohio', '2018-05-08', null, 'Yes', '16');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Oklahoma', '2018-06-26', '2018-08-28', 'No', '5');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Oregon', '2018-05-15', null, 'No', '5');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Pennsylvania', '2018-05-15', null, 'Yes', '18');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Puerto Rico', null, null, null, '1 Resident');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Rhode Island', '2018-09-12', null, 'Yes', '2');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('South Carolina', '2018-06-12', '2018-06-26', 'No', '7');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('South Dakota', '2018-06-05', null, 'No', '1');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Tennessee', '2018-08-02', null, 'Yes', '9');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Texas', '2018-03-06', '2018-05-22', 'Yes', '36');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Utah', '2018-06-26', null, 'Yes', '4');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Vermont', '2018-08-14', null, 'Yes', '1');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Virgin Islands', '2018-08-04', null, null, '1 Delegate');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Virginia', '2018-06-12', null, 'Yes', '11');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Washington', '2018-08-07', null, 'Yes', '10');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('West Virginia', '2018-05-08', null, 'Yes', '3');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Wisconsin', '2018-08-14', null, 'Yes', '8');
INSERT INTO elections(statename, electiondate, runoffdate, senate, representatives) VALUES ('Wyoming', '2018-08-21', null, 'Yes', '1');